// <auto-generated />
using System;
using Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(DocumentDbContext))]
    [Migration("20251129120000_AddPasswordResetTokens")]
    partial class AddPasswordResetTokens
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // This file intentionally minimal. The migration operations are defined in the main migration file.
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");
        }
    }
}
