// <auto-generated />
using System;
using Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(CatalogDBContext))]
    [Migration("20251125231547_UpdateToNet8")]
    partial class UpdateToNet8
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Backend.Models.Category", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedAt = new DateTime(2025, 11, 25, 18, 15, 46, 702, DateTimeKind.Local).AddTicks(1479),
                            Name = "Books",
                            UpdatedAt = new DateTime(2025, 11, 25, 18, 15, 46, 702, DateTimeKind.Local).AddTicks(1514)
                        },
                        new
                        {
                            Id = 2L,
                            CreatedAt = new DateTime(2025, 11, 25, 18, 15, 46, 702, DateTimeKind.Local).AddTicks(1518),
                            Name = "Movies",
                            UpdatedAt = new DateTime(2025, 11, 25, 18, 15, 46, 702, DateTimeKind.Local).AddTicks(1519)
                        },
                        new
                        {
                            Id = 3L,
                            CreatedAt = new DateTime(2025, 11, 25, 18, 15, 46, 702, DateTimeKind.Local).AddTicks(1520),
                            Name = "Music",
                            UpdatedAt = new DateTime(2025, 11, 25, 18, 15, 46, 702, DateTimeKind.Local).AddTicks(1521)
                        },
                        new
                        {
                            Id = 4L,
                            CreatedAt = new DateTime(2025, 11, 25, 18, 15, 46, 702, DateTimeKind.Local).AddTicks(1523),
                            Name = "Games",
                            UpdatedAt = new DateTime(2025, 11, 25, 18, 15, 46, 702, DateTimeKind.Local).AddTicks(1524)
                        },
                        new
                        {
                            Id = 5L,
                            CreatedAt = new DateTime(2025, 11, 25, 18, 15, 46, 702, DateTimeKind.Local).AddTicks(1525),
                            Name = "Electronics",
                            UpdatedAt = new DateTime(2025, 11, 25, 18, 15, 46, 702, DateTimeKind.Local).AddTicks(1526)
                        },
                        new
                        {
                            Id = 6L,
                            CreatedAt = new DateTime(2025, 11, 25, 18, 15, 46, 702, DateTimeKind.Local).AddTicks(1528),
                            Name = "Computers",
                            UpdatedAt = new DateTime(2025, 11, 25, 18, 15, 46, 702, DateTimeKind.Local).AddTicks(1529)
                        },
                        new
                        {
                            Id = 7L,
                            CreatedAt = new DateTime(2025, 11, 25, 18, 15, 46, 702, DateTimeKind.Local).AddTicks(1530),
                            Name = "Home",
                            UpdatedAt = new DateTime(2025, 11, 25, 18, 15, 46, 702, DateTimeKind.Local).AddTicks(1531)
                        },
                        new
                        {
                            Id = 8L,
                            CreatedAt = new DateTime(2025, 11, 25, 18, 15, 46, 702, DateTimeKind.Local).AddTicks(1532),
                            Name = "Garden",
                            UpdatedAt = new DateTime(2025, 11, 25, 18, 15, 46, 702, DateTimeKind.Local).AddTicks(1533)
                        },
                        new
                        {
                            Id = 9L,
                            CreatedAt = new DateTime(2025, 11, 25, 18, 15, 46, 702, DateTimeKind.Local).AddTicks(1534),
                            Name = "Tools",
                            UpdatedAt = new DateTime(2025, 11, 25, 18, 15, 46, 702, DateTimeKind.Local).AddTicks(1535)
                        },
                        new
                        {
                            Id = 10L,
                            CreatedAt = new DateTime(2025, 11, 25, 18, 15, 46, 702, DateTimeKind.Local).AddTicks(1537),
                            Name = "Grocery",
                            UpdatedAt = new DateTime(2025, 11, 25, 18, 15, 46, 702, DateTimeKind.Local).AddTicks(1538)
                        },
                        new
                        {
                            Id = 11L,
                            CreatedAt = new DateTime(2025, 11, 25, 18, 15, 46, 702, DateTimeKind.Local).AddTicks(1539),
                            Name = "Health",
                            UpdatedAt = new DateTime(2025, 11, 25, 18, 15, 46, 702, DateTimeKind.Local).AddTicks(1540)
                        },
                        new
                        {
                            Id = 12L,
                            CreatedAt = new DateTime(2025, 11, 25, 18, 15, 46, 702, DateTimeKind.Local).AddTicks(1541),
                            Name = "Beauty",
                            UpdatedAt = new DateTime(2025, 11, 25, 18, 15, 46, 702, DateTimeKind.Local).AddTicks(1542)
                        },
                        new
                        {
                            Id = 13L,
                            CreatedAt = new DateTime(2025, 11, 25, 18, 15, 46, 702, DateTimeKind.Local).AddTicks(1543),
                            Name = "Toys",
                            UpdatedAt = new DateTime(2025, 11, 25, 18, 15, 46, 702, DateTimeKind.Local).AddTicks(1544)
                        });
                });

            modelBuilder.Entity("Backend.Models.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Post");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "Content 1",
                            Title = "Post 1"
                        },
                        new
                        {
                            Id = 2,
                            Content = "Content 2",
                            Title = "Post 2"
                        },
                        new
                        {
                            Id = 3,
                            Content = "Content 3",
                            Title = "Post 3"
                        },
                        new
                        {
                            Id = 4,
                            Content = "Content 4",
                            Title = "Post 4"
                        });
                });

            modelBuilder.Entity("Backend.Models.PostTag", b =>
                {
                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.Property<int>("TagId")
                        .HasColumnType("int");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.HasKey("PostId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("PostTag");

                    b.HasData(
                        new
                        {
                            PostId = 1,
                            TagId = 1,
                            Id = 0
                        },
                        new
                        {
                            PostId = 1,
                            TagId = 2,
                            Id = 0
                        },
                        new
                        {
                            PostId = 2,
                            TagId = 2,
                            Id = 0
                        },
                        new
                        {
                            PostId = 2,
                            TagId = 3,
                            Id = 0
                        });
                });

            modelBuilder.Entity("Backend.Models.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CategoryId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImgUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CategoryId = 1L,
                            CreatedAt = new DateTime(2025, 11, 25, 18, 15, 46, 702, DateTimeKind.Local).AddTicks(1566),
                            Description = "Description 1",
                            Name = "Product 1",
                            Price = 1.99,
                            UpdatedAt = new DateTime(2025, 11, 25, 18, 15, 46, 702, DateTimeKind.Local).AddTicks(1567)
                        },
                        new
                        {
                            Id = 2L,
                            CategoryId = 2L,
                            CreatedAt = new DateTime(2025, 11, 25, 18, 15, 46, 702, DateTimeKind.Local).AddTicks(1570),
                            Description = "Description 2",
                            Name = "Product 2",
                            Price = 2.9900000000000002,
                            UpdatedAt = new DateTime(2025, 11, 25, 18, 15, 46, 702, DateTimeKind.Local).AddTicks(1571)
                        },
                        new
                        {
                            Id = 3L,
                            CategoryId = 3L,
                            CreatedAt = new DateTime(2025, 11, 25, 18, 15, 46, 702, DateTimeKind.Local).AddTicks(1573),
                            Description = "Description 3",
                            Name = "Product 3",
                            Price = 3.9900000000000002,
                            UpdatedAt = new DateTime(2025, 11, 25, 18, 15, 46, 702, DateTimeKind.Local).AddTicks(1574)
                        },
                        new
                        {
                            Id = 4L,
                            CategoryId = 4L,
                            CreatedAt = new DateTime(2025, 11, 25, 18, 15, 46, 702, DateTimeKind.Local).AddTicks(1575),
                            Description = "Description 4",
                            Name = "Product 4",
                            Price = 4.9900000000000002,
                            UpdatedAt = new DateTime(2025, 11, 25, 18, 15, 46, 702, DateTimeKind.Local).AddTicks(1576)
                        },
                        new
                        {
                            Id = 5L,
                            CategoryId = 5L,
                            CreatedAt = new DateTime(2025, 11, 25, 18, 15, 46, 702, DateTimeKind.Local).AddTicks(1578),
                            Description = "Description 5",
                            Name = "Product 5",
                            Price = 5.9900000000000002,
                            UpdatedAt = new DateTime(2025, 11, 25, 18, 15, 46, 702, DateTimeKind.Local).AddTicks(1579)
                        },
                        new
                        {
                            Id = 6L,
                            CategoryId = 6L,
                            CreatedAt = new DateTime(2025, 11, 25, 18, 15, 46, 702, DateTimeKind.Local).AddTicks(1580),
                            Description = "Description 6",
                            Name = "Product 6",
                            Price = 6.9900000000000002,
                            UpdatedAt = new DateTime(2025, 11, 25, 18, 15, 46, 702, DateTimeKind.Local).AddTicks(1581)
                        },
                        new
                        {
                            Id = 7L,
                            CategoryId = 7L,
                            CreatedAt = new DateTime(2025, 11, 25, 18, 15, 46, 702, DateTimeKind.Local).AddTicks(1583),
                            Description = "Description 7",
                            Name = "Product 7",
                            Price = 7.9900000000000002,
                            UpdatedAt = new DateTime(2025, 11, 25, 18, 15, 46, 702, DateTimeKind.Local).AddTicks(1584)
                        },
                        new
                        {
                            Id = 8L,
                            CategoryId = 8L,
                            CreatedAt = new DateTime(2025, 11, 25, 18, 15, 46, 702, DateTimeKind.Local).AddTicks(1585),
                            Description = "Description 8",
                            Name = "Product 8",
                            Price = 8.9900000000000002,
                            UpdatedAt = new DateTime(2025, 11, 25, 18, 15, 46, 702, DateTimeKind.Local).AddTicks(1586)
                        });
                });

            modelBuilder.Entity("Backend.Models.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("TagName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tag");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            TagName = "Tag 1"
                        },
                        new
                        {
                            Id = 2,
                            TagName = "Tag 2"
                        },
                        new
                        {
                            Id = 3,
                            TagName = "Tag 3"
                        });
                });

            modelBuilder.Entity("Backend.Models.PostTag", b =>
                {
                    b.HasOne("Backend.Models.Post", "Post")
                        .WithMany("PostTags")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Backend.Models.Tag", "Tag")
                        .WithMany("PostTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("Backend.Models.Product", b =>
                {
                    b.HasOne("Backend.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Backend.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("Backend.Models.Post", b =>
                {
                    b.Navigation("PostTags");
                });

            modelBuilder.Entity("Backend.Models.Tag", b =>
                {
                    b.Navigation("PostTags");
                });
#pragma warning restore 612, 618
        }
    }
}
