// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;

#nullable disable

namespace Backend.Migrations
{
    [DbContext(typeof(Backend.Data.DocumentDbContext))]
    partial class AddPasswordResetTokens
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // This file intentionally minimal. The migration operations are defined in the main migration file.
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");
        }
    }
}
